apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-app-of-apps
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/emilyxinyi/kargo-helm
    path: argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd